### ISSUE TITLE
Series.getPoster null values

### ISSUE THREAD

**Issue by Daniele-Comi** [Omertron/api-thetvdb#10]
I discovered that there is the method getPoster in the Series class and I thought it would be useful because it should be quicker than retrieving the entire list of banners for each series.
The problem is that no string is returned, just null everytime.

**Comment by Omertron** [comment]
Hi,

If you get the Series object from the searchSeries method then the poster will be null because it is not populated in the search results, however "banner" is. You can see this here:
http://thetvdb.com/api/GetSeries.php?seriesname=Agents

You will have to cycle round the results and getSeries information to get posters.
